### ISSUE TITLE
Some model files are not provided？

### ISSUE THREAD

**Issue by Gus233** [prip-lab/MSU-LatentAFIS#1]
Hello, I'm trying to run the system，but I have some difficulties.  
I encountered such a mistake  when extracting the template, No module names resnet.
It seems that  the resnet.py, preactresnet.py, bcnn.py, inception_resnet_v1.py and net_compress.py in extraction/ are not provided, and the CompNet in the net_compress.py is needed when setup the model in the descriptor_DR.py.
I don't know how to solve this problem and I wonder whether I'm running the code incorrectly.
Thank you.

**Comment by luannd** [comment]
Hi @Gus233 ,

Which script did you run? And what command line did you use? That information will be more clear to me. Thanks!

**Comment by Gus233** [comment]
> Hi @Gus233 ,
> Which script did you run? And what command line did you use? That information will be more clear to me. Thanks!

This script:  python extraction latent.py --idir --tdir
And the command line in the  extraction/models/ __init__.py

**Comment by luannd** [comment]
I add the missing files. Pl. try again.
The script should be like this: 
`python extraction_latent.py --idir='/home/Latent/' --tdir='/home/Templates/Latent/'`

**Comment by Gus233** [comment]
The program can run successfully now. Thank you.
