### ISSUE TITLE
Matching scores different from those in the User Guide？

### ISSUE THREAD

**Issue by Gus233** [prip-lab/MSU-LatentAFIS#2]
I performed fingerprint matching with the codebook in the folder LatentAFIS/extraction/. 
When matching the NIST SD27 dataset, the average/ maximum genuine scores are quite different from those written in the User Guide.  I found that the genuine scores of the same three fingerprints in the sample data are  the same with those in the sample_scores.txt.   But the scores of  fingerprints in Fig.4  are different. The scores of these four fingerprints are 136.173, 216.857, 20.065 and 54.907, respectively.
I wonder if there is something wrong with the codebook or the User Guide.

**Comment by luannd** [comment]
Did you enroll Latents with `extraction_latent` and Rolled prints with `extraction_rolled` scripts? 
Did you have the original NIST SD27 dataset?
Scores also depend on the pre-processing stage. Do you get the same rank as in Fig 4?
Do you obtain the rank-1 results as in Fig 3?

Hope those questions can help you figure out. If not, pl. let me know.

**Comment by Gus233** [comment]
I tested on the NIST SD27 dataset.  The template file  generated by  latent image 001.bmp in the database has the same size 980.1kB with that generated by the good_latent.bmp in sample data. And the matching scores  of the 001.bmp, 093.bmp,186.bmp in the dataset are 36.574, 70.333,  35.661, respectively, which are the same with those of fingerprints in the sample data. Therefore,  there should be no problem with the dataset.
I have not got the same rank. The fingerprints in Fig.4 returned at rank 1,1,2 and 1, probably due to different scores. 
I felt it confusing that the matching scores of  001.bmp, 093.bmp,186.bmp are the same with those in the sample data, but the matching scores of 007.bmp, 015.bmp, 005.bmp and 018.bmp are different from those of fingerprints in Fig. 4 since these fingerprints are processed in the same way.
When computing the matching scores,  matching of several latent fingerprints failed  due to empty latent templates.  So I excluded these data when computing the CMC curves. The rank-1 rate is 0.80, which is different from that in Fig.3. When these data are retained, the rank-1 rate is 79.07.
Besides, there are two codebooks with same name in /matching/ and /extraction/, respectively, and several matching scores computed by them are different.

**Comment by luannd** [comment]
Could you send us the score file the algorithm generated? Since there are no empty latent templates in our experiments, so there should be a problem while running the code.

**Comment by Gus233** [comment]
I am sorry that I don't know how to attach the score file on github, so I sent an email.  Thank you for taking your time.

**Comment by ud38** [comment]
HI can someone share NIST SD27 rolled tenprint database
