### ISSUE TITLE
Bug in get_maps.py

### ISSUE THREAD

**Issue by handyzeng** [prip-lab/MSU-LatentAFIS#4]
In function "get_quality_map_dict" and "get_quality_map_dict_coarse":

            patch[patch > t] = 0.0
            patch[patch < -t] = -0.0

SHOULD BE:
            patch[patch > t] = t
            patch[patch < -t] = -t

**Comment by ctymoszek** [comment]
This software is no longer being worked on or maintained, so unfortunately we are not able to advise on this.
