### ISSUE TITLE
Something wrong when loading dim_reduction model

### ISSUE THREAD

**Issue by whqwill** [prip-lab/MSU-LatentAFIS#5]
Something wrong when loading dim_reduction model:

RuntimeError: Error(s) in loading state_dict for CompNet:
	Missing key(s) in state_dict: "layer3.1.running_var", "layer3.1.bias", "layer3.1.running_mean". 
	size mismatch for layer1.1.num_batches_tracked: copying a param with shape torch.Size([96, 96]) from checkpoint, the shape in current model is torch.Size([]).
	size mismatch for layer2.layers.0.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([96, 96]).
	size mismatch for layer2.layers.1.running_var: copying a param with shape torch.Size([96, 96]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for layer2.layers.3.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([96, 96]).
	size mismatch for layer2.layers.4.running_mean: copying a param with shape torch.Size([96, 96]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for layer3.0.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([96, 96]).

How to solve it ????

**Comment by FrenchBulldogTW** [comment]
I'm dealing with that same problem.

**Comment by takahashi333** [comment]
I have the same problem.
Maybe the parameters are mismatch for networks.

**Comment by Vidushi1107** [comment]
I am also facing the same problem.

**Comment by FrenchBulldogTW** [comment]
It's Pytorch version issue. You can add filtered in load_model().
```
<descriptor_DR.py>
def load_model(model, filename, cuda):
    ........................
    for key_model in list(model):
        model_dict = model[key_model].state_dict()
        update_dict = {}
        valid_keys = list(model_dict)
        for i, key in enumerate(state_dict[key_model]):
            update_dict[valid_keys[i]] = state_dict[key_model][key]

        filtered = {k: v for k, v in state_dict[key_model].items() 
                if (k in model[key_model].state_dict()) and (model[key_model].state_dict()[k].shape == state_dict[key_model][k].shape)} 
    model[key_model].load_state_dict(filtered)
```

**Comment by Vidushi1107** [comment]
> It's Pytorch version issue. You can add filtered in load_model().
> 
> ```
> <descriptor_DR.py>
> def load_model(model, filename, cuda):
>     ........................
>     for key_model in list(model):
>         model_dict = model[key_model].state_dict()
>         update_dict = {}
>         valid_keys = list(model_dict)
>         for i, key in enumerate(state_dict[key_model]):
>             update_dict[valid_keys[i]] = state_dict[key_model][key]
> 
>         filtered = {k: v for k, v in state_dict[key_model].items() 
>                 if (k in model[key_model].state_dict()) and (model[key_model].state_dict()[k].shape == state_dict[key_model][k].shape)} 
>     model[key_model].load_state_dict(filtered)
> ```

Thanks! It worked.

**Comment by FrenchBulldogTW** [comment]
Take care, there're lots of version issue.

**Comment by ctymoszek** [comment]
This software is no longer being worked on or maintained, so unfortunately we are not able to advise on this.
