### ISSUE TITLE
Unable to generate scores for some latent template

### ISSUE THREAD

**Issue by Vidushi1107** [prip-lab/MSU-LatentAFIS#6]
I am facing some issue while generating the score file.

ERROR : 
**Latent minutiae templates: 8
Latent texture templates: 0
Matching failed: latent template is empty. Skipping.**

I reduced the number of the Latent minutiae templates to be allowed, to generate scores by making some changes in the code **matchers.cpp in line 380** :

**vector<int> selected_ind{27-1, 3-1, 12-1};
if(latent_template.m_nrof_minu_templates<=selected_ind[0] && latent_template.m_nrof_texture_templates<=0)
{
return 1;
}**

to 
 
**vector<int> selected_ind{27-1, 3-1, 12-1};
if(latent_template.m_nrof_minu_templates<=selected_ind[1] && latent_template.m_nrof_texture_templates<=0)
{
return 1;
}**

i.e. I just changed the minimum number of minutiae to be 3-1 = 2 by selecting the selected_ind[1] instead of selected_ind[0].

But then I got this issue :

**Assertion error in line 433: assert(des_len == latent_minu_template.m_des_length);**

Can someone please tell , what is wrong in this ?

**Comment by ctymoszek** [comment]
This software is no longer being worked on or maintained, so unfortunately we are not able to advise on this.
