### ISSUE TITLE
cannot create environment with conda and environment.yml

### ISSUE THREAD

**Issue by nmarandi** [prip-lab/MSU-LatentAFIS#7]
when  I run `conda env create -n latentafis -f environment.yml`, it ends with many package dependency conflicts error. 
I use ubuntu 16.04 and the latest miniconda for python2.7. 

for example one of the package conflicts:

`Package mpfr conflicts for:
gmpy2==2.0.8=py27h10f8cd9_2 -> mpfr[version='>=4.0.1,<5.0a0']
mpfr==4.0.1=hdf1c602_3
mpc==1.1.0=h10f8cd9_1 -> mpfr[version='>=4.0.1,<5.0a0']
sympy==1.3=py27_0 -> gmpy2[version='>=2.0.8'] -> mpfr[version='3.*|>=4.0.1,<5.0a0|>=4.0.2,<5.0a0']
gmpy2==2.0.8=py27h10f8cd9_2 -> mpc -> mpfr[version='3.*|>=4.0.2,<5.0a0|4.*']`

**Comment by ctymoszek** [comment]
@nmarandi This software is no longer being worked on or maintained, so unfortunately we are not able to advise on this. It is possible that some conflicts have developed with the dependencies.
